spring:
  docker:
    compose:
      file: src/main/resources/dc/dev-env.yml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

---
global:
  search:
    sort-field: id
    limit: 30
    sort-direction: asc

customer:
  search:
    sort-field: name
    limit: 20
    sort-direction: asc
