spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5433}/${DB_NAME:store}
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}
  application:
    name: store-dev

---
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:43200000} # 1/2 day
      refreshExpiration: ${JWT_REFRESH_EXPIRATION:259200000}  # 3 days
      token-prefix: "Bearer "

