spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${user}
    password: ${pass}
  application:
    name: store

---
application:
  security:
    jwt:
      token-prefix: "Bearer "
      secret-key: ${SECRET_KEY}
      expiration: ${JWT_EXPIRE}
      refreshExpiration: ${JWT_REFRESH_EXPIRATION:259200000}  # 3 days